### PR TITLE
issues #45 and #50

### PR DESCRIPTION
**Pull request by rubengc**
More accurate css selectors
edd_wl_query_args filter on edd_wl_get_query function

### CODE REVIEW

**Comment by michaelbeil** [comment]
#45 and #50

**Comment by rubengc** [comment]
Thanks @michaelbeil 

Fixed :)

**Comment by rubengc** [comment]
@sumobi what do you think? Is it ready to merge?

**Comment by sumobi** [comment]
@rubengc Sorry for the delay, still travelling. Will check it out as soon as I can.

**Comment by rubengc** [comment]
not problem @sumobi 👍

**Comment by rubengc** [comment]
remindor to @sumobi 😢

**Comment by rubengc** [comment]
ding @sumobi

**Comment by sumobi** [comment]
Merged! sorry for the delay :)

**Pull request merged**
